/* SPDX-License-Identifier: GPL-2.0-or-later */
/*
 * Experimental wasm64 TCG backend runtime boundary.
 *
 * This header defines the C-side contract for generated WebAssembly
 * translation blocks.  The backend is intentionally fail-closed until
 * instruction lowering, helper calls, memory access, and invalidation are
 * implemented and tested.
 */

#ifndef TCG_WASM64_H
#define TCG_WASM64_H

#include <stdint.h>

typedef struct CPUArchState CPUArchState;

/*
 * Execution counters reported by the experimental backend.
 *
 * These counters are part of the fallback contract: every generated block
 * attempt must be explainable as a generated execution, a compile/cache event,
 * or a precise fallback to the existing TCI/native execution path.
 */
typedef struct TCGWasm64Counters {
    uint64_t generated_attempts;
    uint64_t generated_compiled;
    uint64_t generated_executed;
    uint64_t generated_cache_hits;
    uint64_t generated_coverage_numerator;
    uint64_t generated_coverage_denominator;
    uint64_t translated_tbs;
    uint64_t translated_ops;
    uint64_t translated_fallback_markers;
    uint64_t translated_metadata_misses;
    uint64_t translated_profiled_tbs;
    uint64_t translated_lowerable_tbs;
    uint64_t translated_profile_supported_ops;
    uint64_t translated_profile_unsupported_ops;
    uint64_t translated_generated_candidate_tbs;
    uint64_t translated_generated_supported_ops;
    uint64_t translated_generated_unsupported_ops;
    uint64_t translated_generated_output_tbs;
    uint64_t translated_generated_output_bytes;
    uint64_t translated_generated_output_ops;
    uint64_t translated_generated_output_truncated;
    uint64_t fallback_unsupported;
    uint64_t fallback_helper;
    uint64_t fallback_qemu_load;
    uint64_t fallback_qemu_store;
    uint64_t fallback_runtime;
} TCGWasm64Counters;

typedef enum TCGWasm64FallbackReason {
    TCG_WASM64_FALLBACK_UNSUPPORTED,
    TCG_WASM64_FALLBACK_HELPER,
    TCG_WASM64_FALLBACK_QEMU_LOAD,
    TCG_WASM64_FALLBACK_QEMU_STORE,
    TCG_WASM64_FALLBACK_RUNTIME,
} TCGWasm64FallbackReason;

#define TCG_WASM64_TB_METADATA_MAGIC 0x36574153u /* "SAW6" */
#define TCG_WASM64_TB_METADATA_VERSION 1u

typedef enum TCGWasm64TBMetadataFlags {
    TCG_WASM64_TB_METADATA_VALID = 1u << 0,
    TCG_WASM64_TB_METADATA_FALLBACK = 1u << 1,
    TCG_WASM64_TB_METADATA_LOWERING_PROFILE = 1u << 2,
    TCG_WASM64_TB_METADATA_PROFILE_LOWERABLE = 1u << 3,
    TCG_WASM64_TB_METADATA_GENERATED_CANDIDATE = 1u << 4,
    TCG_WASM64_TB_METADATA_TERMINAL = 1u << 5,
    TCG_WASM64_TB_METADATA_GENERATED_OUTPUT = 1u << 6,
    TCG_WASM64_TB_METADATA_OUTPUT_TRUNCATED = 1u << 7,
} TCGWasm64TBMetadataFlags;

typedef enum TCGWasm64TranslateFallbackReason {
    TCG_WASM64_TRANSLATE_FALLBACK_NONE = 0,
    TCG_WASM64_TRANSLATE_FALLBACK_NO_WASM_EMITTER = 1,
    TCG_WASM64_TRANSLATE_FALLBACK_UNSUPPORTED_OPCODE = 2,
} TCGWasm64TranslateFallbackReason;

#define TCG_WASM64_LOWERING_PROFILE_HOTBLOCK 1u
#define TCG_WASM64_TRANSLATE_OUTPUT_MAX 4096u

/*
 * Side-band metadata recorded while the wasm64 target emits the fallback TCI
 * bytecode stream.  This is the bridge from the current fallback-only target
 * to a translation-time WebAssembly emitter: future lowering should attach
 * generated bytes here, while unsupported TBs keep an explicit fallback marker.
 */
typedef struct TCGWasm64TBMetadata {
    const void *tb_ptr;
    uint32_t magic;
    uint32_t version;
    uint32_t flags;
    uint32_t op_count;
    uint32_t first_op;
    uint32_t last_op;
    uint32_t first_unsupported_op;
    uint32_t fallback_reason;
    uint32_t lowering_profile;
    uint32_t supported_op_count;
    uint32_t unsupported_op_count;
    uint32_t generated_supported_op_count;
    uint32_t generated_unsupported_op_count;
    uint32_t generated_output_size;
    uint32_t generated_output_op_count;
    uint32_t generated_output_checksum;
    const uint8_t *generated_output;
} TCGWasm64TBMetadata;

void tcg_wasm64_counters_reset(TCGWasm64Counters *counters);
void tcg_wasm64_counters_add(TCGWasm64Counters *dst,
                             const TCGWasm64Counters *src);
void tcg_wasm64_count_fallback(TCGWasm64Counters *counters,
                               TCGWasm64FallbackReason reason);
void tcg_wasm64_translate_begin(const void *tb_ptr);
void tcg_wasm64_translate_note_tci_op(uint32_t op);
void tcg_wasm64_translate_note_tci_insn(uint32_t op, uint32_t insn);
const TCGWasm64TBMetadata *tcg_wasm64_translate_lookup(const void *tb_ptr);
bool tcg_wasm64_translate_generated_candidate(
    const TCGWasm64TBMetadata *metadata);
bool tcg_wasm64_translate_generated_output_available(
    const TCGWasm64TBMetadata *metadata);
bool tcg_wasm64_backend_available(void);

/*
 * Context shared between QEMU and a generated WebAssembly TB function.
 *
 * The generated function receives exactly one pointer to this structure.  This
 * keeps the call ABI small enough for browser function-table calls and leaves
 * room for helper-call, stack, and dispatch state without changing the
 * generated function signature.
 */
typedef struct TCGWasm64Context {
    void *tb_ptr;
    void *next_tb_ptr;
    void *env;
    uint64_t *stack;
    void *ret128;
    TCGWasm64Counters *counters;
    uintptr_t regs;
    uintptr_t ret;
    uint32_t flags;
} TCGWasm64Context;

typedef uintptr_t (*TCGWasm64TBFunc)(TCGWasm64Context *ctx);

typedef struct TCGWasm64Instance {
    void *tb_ptr;
    TCGWasm64TBFunc func;
} TCGWasm64Instance;

/*
 * Header stored at the start of each wasm64 backend translation block.
 *
 * Cold blocks must remain runnable through the existing fallback path until a
 * generated instance has been compiled and installed for the current thread.
 */
typedef struct TCGWasm64TBHeader {
    void *fallback_ptr;
    void *wasm_ptr;
    uint32_t wasm_size;
    void *imports_ptr;
    uint32_t imports_size;
    int32_t *counters;
    TCGWasm64Instance **instances;
} TCGWasm64TBHeader;

uintptr_t tcg_wasm64_tb_exec(CPUArchState *env, const void *tb_ptr,
                             TCGWasm64Counters *counters);
TCGWasm64Counters *tcg_wasm64_active_counters(void);
void tcg_wasm64_report_summary(const char *reason,
                               const TCGWasm64Counters *counters);

#endif /* TCG_WASM64_H */
